title: Title of your CV site
profile_img: assets/img/profile.webp
icon_img: assets/img/icon.webp

phone_number: 012-345-6789
address: 123 Broadway, City, State, 012345, Country

email: your-email@example.com
linkedin_username: linkedin
github_username: github
instagram_username: instagram
twitter_username: twitter
facebook_username: facebook
youtube_username: youtube
blog_url: your-homepage-url